### ISSUE TITLE
Instructions needed for how to get a non-executable running on a new computer 

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#100]
STORY:
As a new user of the software, I need step-by-step instructions for how to download Domino and get it running on my computer.  What additional software is required?  Where should the files be stored? What changes to the environment variable are required etc.

**Comment by jeff101** [comment]
Is this specifically for in-house testing? Or do you propose that an end user may want to run our software via their own python installation, not from a "compiled" exe? If it's just for in house purposes, here are the instructions I put together:
https://docs.google.com/document/d/1XTJbaWQCGlz6biqpjBedaM95eXBzJDoDuvx9tnO_Ktc/edit?usp=sharing

**Comment by Nickel33** [comment]
In house is fine for now.

**Comment by Nickel33** [comment]
I added the instruction link to the Readme for Domino.
