### ISSUE TITLE
Hard Crash on USB disconnect

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#103]
I unplugged the logger and Python stopped responding. Here is the error message:

![image](https://user-images.githubusercontent.com/3340259/50700365-5d2cfe00-1018-11e9-8d87-95c2cfff5fd7.png)

**Comment by jeff101** [comment]
I believe this has been fixed in the mat library. You need to remove your venv folder and make will automatically download the latest.

**Comment by Nickel33** [comment]
Verified fixed in 0.5.8. Closing.
