### ISSUE TITLE
Unclear what is happening when logger connected but port is busy

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#104]
If the logger is being used by another application OR if the logger is unresponsive on the COM port, Domino can get stuck where it is neither connected or disconnected.  I think that some of these are default values and they need to be changed.  None of the fields should be filled in.  It should not say that the device is running etc.  In addition, the stop and start buttons should BOTH be disabled.

![image](https://user-images.githubusercontent.com/3340259/50702215-3b367a00-101e-11e9-971c-531e79bfe02b.png)

To re-create, connect with matconfig and then run Domino.

**Comment by jeff101** [comment]
I believe this is now outdated

**Comment by Nickel33** [comment]
The behavior looks logical and clear in 0.5.8. Closing.
