### ISSUE TITLE
Make NOAA declination calculator link live

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#109]
Story:
As a user who wants to correct heading for magnetic declination, I want to be able to easily get the help I need. 

Details:
In the "About Declination" help dialog box, there is a link.  It should be clickable.  If not, then it should at least be able to be copied and pasted.

**Comment by jeff101** [comment]
This is fixed on the live_links branch

**Comment by jeff101** [comment]
Now on master

**Comment by Nickel33** [comment]
Other than the fact that the government's page is shut down, this works.  PR 115.
