### ISSUE TITLE
Add a "secret" connect/disconnect button

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#123]
TODO
As production engineer, I work with multiple software applications that need to talk to the MAT logger when assembling, calibrating, and testing. Domino is "greedy" with the com port, meaning that as soon as a MAT logger is discovered, a connection is opened and other software applications are unable to talk to the logger. If I want to use another application, I have to close Domino so it gives up the port. 

DONE
Add a way for me to close the connection, and have it stay closed, until I open it again, and keep it hidden as to not confuse end users.

**Comment by jeff101** [comment]
On Domino-123

**Comment by Nickel33** [comment]
Not fixed.  COM port remains open after CNTRL-Click.

**Comment by jeff101** [comment]
on branch Domino-123_take_2

**Comment by jeff101** [comment]
by the way, see the status bar for the status of the manual connection. It will display either "Auto Connect" or "Manually Disconnected"

**Comment by Nickel33** [comment]
Fixed. 0.5.8. Closing.
