### ISSUE TITLE
Add valid data files (.lid) and known good output files (.txt) to automated test routine

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#125]
The attachment contains 8 known good .lid files and 27 known good text files.  These files should be used to  further improve the test coverage.  Each text file has the settings that were used to create the file in the file name.

[goodfilesfortravis.zip](https://github.com/LowellInstruments/Domino/files/2792712/goodfilesfortravis.zip)

**Comment by jeff101** [comment]
Good files have been added to 0.6.3. More would be better, but at least it's a start.
