### ISSUE TITLE
Hard Crash Domino 0.5.0

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#136]
Unplugged logger and got this crash.

![image](https://user-images.githubusercontent.com/3340259/52591554-3c737780-2e12-11e9-9d19-ac41fa3ca984.png)

**Comment by jeff101** [comment]
I'm guessing this is the same as 103. I'm going to close this bug (136) and address it in 103.

**Comment by Nickel33** [comment]
I have not seen this error with 0.5.8.  Will reopen if it comes up again.  Closing for now.
