### ISSUE TITLE
Remove non-standard tilt-to-speed curves from Domino

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#143]
Remove the prototype/non standard TCM tilt-to-speed model types from the "Meter Model" drop down.

Supported models are the:
TCM-1 fresh/salt with 0, 1, 3 range weights (6 total)
TCM-3 salt (1 total)
TCM-4 fresh/salt (2 total)

**Comment by jeff101** [comment]
On branch Domino-143

**Comment by Nickel33** [comment]
Fixed. 0.5.8. Closing.
