### ISSUE TITLE
Computer clock runs and buttons are not disabled when device is not connected

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#152]
![image](https://user-images.githubusercontent.com/8093093/55007905-94c39a80-4fb6-11e9-91b5-821861f853da.png)

**Comment by Nickel33** [comment]
Two of the buttons are still enabled. Back to Jeff.

![image](https://user-images.githubusercontent.com/3340259/61831079-c3edf980-ae3a-11e9-8ba3-029a59314035.png)

**Comment by Nickel33** [comment]
Verified fixed 0.6.0.1.
