### ISSUE TITLE
Installer: Don't load driver on Windows 10, not needed

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#159]
Story:  As a windows 10 unser, it is not necessary to load the Windows 10 CDC driver.  When the installer attempts to load it, and it fails, I am confused and think something went wrong.

Background:  Windows 10 includes CDC (serial) support natively (as of update??) .  It is not needed.  The driver should be loaded for Windows 7 & 8.  For Windows 7 it should work.  For Windows 8 it will throw an error and they will need to manually load the driver by following the Windows 8 driver loading procedure available on the lowellinstruments.com website under FAQs.

**Comment by jeff101** [comment]
I think I have this fixed but I don't have a Windows 10 machine.

**Comment by Nickel33** [comment]
Not fixed in Windows 10.

![image](https://user-images.githubusercontent.com/3340259/57634188-cd253500-7572-11e9-818d-88729d12e828.png)

**Comment by Nickel33** [comment]
New message: 
![image](https://user-images.githubusercontent.com/3340259/61406849-b240ab00-a8aa-11e9-9a94-65954dfae375.png)

**Comment by jeff101** [comment]
I have this working on my Windows 8 computer but I need to test it on Windows 10. On the second last line of the innosetup script, change 
Filename: "{app}\drivers\dpinst.exe"; OnlyBelowVersion: 0,10
to (remove 0,)
Filename: "{app}\drivers\dpinst.exe"; OnlyBelowVersion: 10

**Comment by Nickel33** [comment]
Verified fixed 0.6.0.1.
