### ISSUE TITLE
File fails to convert or give any warning of failure

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#161]
The attached file does not convert.  No output files, but also no warnings.

[1705202_AT42-06-CM_(0).zip](https://github.com/LowellInstruments/Domino/files/3138109/1705202_AT42-06-CM_.0.zip)

**Comment by jeff101** [comment]
This error caused by the run time being less than a major interval. The partial interval is chopped off, leaving no remaining data to convert.

**Comment by Nickel33** [comment]
It needs to pop up a warning of some kind.

**Comment by jeff101** [comment]
I've added a generic dialog that notifies the user when a conversion error has occurred.

**Comment by Nickel33** [comment]
0.5.8 does not crash and pops up an error.  Closing.
