### ISSUE TITLE
This .lid file crashes Domino when attempting to add to conversion window

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#162]
[PL1RT32_LIT-M_(0) - Copy.zip](https://github.com/LowellInstruments/Domino/files/3153360/PL1RT32_LIT-M_.0.-.Copy.zip)

**Comment by jeff101** [comment]
I found this file by accident while doing some testing. I may have manually corrupted it in the weeks past, but in any case, Domino should handle it gracefully.

**Comment by jeff101** [comment]
Fixed on Domino-165

**Comment by Nickel33** [comment]
0.5.8 does not crash when adding this file.  Closing bug.
