### ISSUE TITLE
lid file crashes Domino when "Convert" is clicked

### ISSUE THREAD

**Issue by richardsc** [LowellInstruments/Domino#164]
Not sure if it's the file, but when I try and convert Domino crashes. Are there logs somewhere that might indicate what is going on?

[1904108_Test_(3).zip](https://github.com/LowellInstruments/Domino/files/3160145/1904108_Test_.3.zip)

**Comment by richardsc** [comment]
Also, this is on Windows 7 (if that might matter).

**Comment by jeff101** [comment]
I'm able to convert this file to all possible output types, with and without averaging enabled. Perhaps one of the bug fixes in the past couple months corrected this problem?

**Comment by richardsc** [comment]
Same result as before for me :cry: 

I click "Convert" and get as below. Are there any kind of program log files that I could send that might indicate what is happening?

![image](https://user-images.githubusercontent.com/233584/61320529-f2872700-a7df-11e9-9b8a-453c48a352af.png)

**Comment by Nickel33** [comment]
This is probably the same issue as #169.  Try release 0.5.8, due out later today (July 18th) and see if it works.

**Comment by jeff101** [comment]
@richardsc , thanks for reporting this bug. I just took a more careful look and Nick was correct; it has the same cause as #169. It was corrected in 0.5.7, however 0.5.8 is now available on Github (not yet on the Lowell Instruments website). https://github.com/LowellInstruments/Domino/releases

**Comment by Nickel33** [comment]
Declaring this issue fixed 0.5.8.

**Comment by richardsc** [comment]
Can confirm that it appears to work! Thanks!
