### ISSUE TITLE
Create Setup File Screen always using default settings, not remembering user settings

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#166]
STORY: As a user, I want my custom configuration settings to the "sticky" in Domino, so when I reopen Domino I don't need to change the values back to my preferred settings every time.

Additional Info:  It appears that Domino is not saving the users values, as is done in MLC.  It should stash those values in App Data for use the next time Domino is opened.

**Comment by jeff101** [comment]
Save all settings including start/stop time

**Comment by Nickel33** [comment]
Verified fixed 0.6.0.1. Closing.
