### ISSUE TITLE
Software crashes on conversion when no domino.dat appdata exists

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#169]
The file split feature is causing a crash on conversion if there isn't an existing domino.dat file in the roaming/Lowell Instruments/ appdata folder.

![image](https://user-images.githubusercontent.com/8093093/61410723-d1dbd180-a8b2-11e9-9493-a07ccf44ce25.png)

**Comment by Nickel33** [comment]
This is fixed in 0.5.8.
