### ISSUE TITLE
Excessive CPU use on 0.5.6 a 0.5.7

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#170]
The CPU use is up around ~30% for versions 0.5.6 and 0.5.7.  The program is running very sluggishly.  Three machines tested Windows 7 and 10.

**Comment by jeff101** [comment]
Through process of elimination, I have discovered this problem is due to code on the "Start/Stop Device" tab.  Now to figure out what the problem is...

**Comment by jeff101** [comment]
Well that was easy. The very first thing I tried fixed it! QThread has a method called sleep. It seems as though a value less than 1 causes the CPU usage to skyrocket. I suspect the function is internally rounding down to the nearest int, in this case 0 seconds, therefore no delay. QThread also has a method called msleep (milisecond sleep). A value of 250 has the CPU usage back under 1%.

**Comment by Nickel33** [comment]
Verified fixed in 0.5.8.
