### ISSUE TITLE
Eliminate Windows SmartScreen Protection

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#173]
Story:  As a user, when I download and install Domino I don't expect to get a scary warning from Windows that the program is risky and should not be run.

Additional comments:  We probably need a code signing certificate.  Also, the installer should not get any hits when scanned at Virustotal.com

**Comment by jeff101** [comment]
Look into code signing certificate. Check out Comodo.

**Comment by jeff101** [comment]
Code signing is up and running. The user will still get a SmartScreen notification, but at least now it will be blue and say the software is from Lowell Instruments.

**Comment by Nickel33** [comment]
Partially fixed.  At least the warning is not as severe and the publisher is shown as Lowell Instruments LLC.  Closing for now.
