### ISSUE TITLE
32K Buffer size warning is falsely indicated when Temperature channel is disabled

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#174]
When the temperature channel is disabled, the buffer size warning is still appearing.  See below:

![image](https://user-images.githubusercontent.com/3340259/61832013-b7b76b80-ae3d-11e9-82cf-35cbeacd1874.png)

**Comment by jeff101** [comment]
This fix requires updating the lowell-mat library

**Comment by Nickel33** [comment]
Verified fixed 0.6.0.1.
