### ISSUE TITLE
Change behavior of Converter Table

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#181]
ConverterTable should not have any responsibilities such as handling conversions and showing dialog boxes. Make it a simple class for manipulating the converter table.

**Comment by jeff101** [comment]
Add a status column
Move "containing folder" all the way to the right
If there are converted and unconverted files, prompt the user to reconvert files, otherwise ignore them
Prompt user to overwrite files; give option to overwrite all remaining files

**Comment by Nickel33** [comment]
A few minor changes:
1. Change column headings in the table to left justified to match the values below them.
2. Make column headings bold or underlined or something to differentiate them from the values below.
3. Make the default width of the "containing folder" column ~50% wider to accommodate longer paths names.
4. Make it more obvious that a file has been converted.  The Status change from "unconverted" to "converted" is too subtle.  Maybe make the whole row a different color or font or highlighted etc.

**Comment by Nickel33** [comment]
Really close.  The only issue that is not done is 2 from above.  The top row of the column needs something else to make it pop.  Can you put a double-underline? Or a single underline and make it dark grey?  See how the top row blends into the table in these shots below:
![image](https://user-images.githubusercontent.com/3340259/62947447-84b72680-bdb0-11e9-9eb3-268c055db1bb.png)

![image](https://user-images.githubusercontent.com/3340259/62947459-8b459e00-bdb0-11e9-8f63-1fc4a8fbc0fe.png)

**Comment by jeff101** [comment]
Interesting, it looks like Windows 10 renders things differently. Here it is on Windows 7.
![image](https://user-images.githubusercontent.com/8093093/63218386-8887d780-c127-11e9-850e-74e12d4bdde8.png)

**Comment by jeff101** [comment]
I'll talk to you about this on Monday

**Comment by Nickel33** [comment]
Looking good. Closing.
