### ISSUE TITLE
Make file conversion status more obvious...

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#196]
The file conversion status is rather subtle, especially if there is an error.  I would like it to be more apparent.  This is especially true for converting one or two small files, or files with errors where the progress bar doesn't stay up for more than a fraction of a second (if at all).

The way I see it, there are three primary status types:

- unconverted
- converted
- Some sort of error: failed (no output file) error (with partial data file) error (with no data file).  

This is what four of the status states looks like now:
![image](https://user-images.githubusercontent.com/3340259/64814528-9c312d00-d571-11e9-904e-d52678b4fe23.png)

What we want to do is differentiate between these three states more clearly.  Everyone will see unconverted and converted so it but an error state should pop up and it should have a sentence of status attached with it.  I suggest the following:

- Ready for Conversion (black text)
- Successfully Converted (with green text)
- Error: Specific Status Here (red text)

If that is too crowded for the space available:

- Ready (Black text)
- Converted (green text)
- Error: Specific Status Here (red text)

What do you think?

**Comment by jeff101** [comment]
I think #195 may have addressed most of these issues. See what you think.

**Comment by Nickel33** [comment]
It is better.  One more change.  Capitalize all the status words:
Converted
Error
Unconverted
etc.

**Comment by Nickel33** [comment]
Looking good.  Closing.
