### ISSUE TITLE
Add "Cable Attitude" as an output type

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#202]
STORY:
As a customer, I have taped my MAT-1 to a cable towed behind a ship. I'm interested to know what angle of the cable (relative to level) and it's axial rotation.

DONE:
Domino should show an output type called "Cable Attitude" that will output what I want.

**Comment by jeff101** [comment]
https://github.com/LowellInstruments/lowell-mat/issues/129 must be completed before closing this issue.

**Comment by jeff101** [comment]
Added to 0.6.3 RC2

**Comment by Nickel33** [comment]
Verified complete.
