### ISSUE TITLE
Divide by zero not handled for bad temperature

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#214]
0.6.3.5  It appears that Domino can not handle a broken/defective temperature sensor.  It will crash and close unexpectedly. See below:

![image](https://user-images.githubusercontent.com/3340259/69187048-cb22cc80-0ae7-11ea-9ac6-7ead0d94c0ef.png)

Done:  Domino does not crash when the temperature sensor returns a zero A/D value.

**Comment by jeff101** [comment]
This error occurs when the raw a/d value is 16 binary ones (65535 decimal). I'm now catching this exception and returning -273.15. This is an arbitrary choice and you may want to choose another "bad value" number.

**Comment by Nickel33** [comment]
Verified fixed.  0.6.4
