### ISSUE TITLE
No battery/bad battery: confusing message

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#220]
0.6.3

When the logger's battery is missing the message is confusing.  "Device is running - Safe Shutdown"
![image](https://user-images.githubusercontent.com/3340259/69453674-660ee700-0d32-11ea-9d53-bef31b5166bf.png)

This is not accurate. In this more the logger returns a status of 0x10.  This indicates the logger has stopped recording because the battery is bad.  In MAT Logger Commander the message is better, but still wrong:
![image](https://user-images.githubusercontent.com/3340259/69453716-8474e280-0d32-11ea-8ddf-ac50620035cd.png)

What the message should read is: Bad battery, replace now.

**Comment by Nickel33** [comment]
Consider adding a new "error" icon in place of the rabbit and hand symbol.  Or just use the hand symbol for this error state.

**Comment by Nickel33** [comment]
There is a similar issue when there is a MAT.cfg error.  The logger is running but stopped at the same time:.
![image](https://user-images.githubusercontent.com/3340259/69460189-81352300-0d41-11ea-980a-be49ead4c0b2.png)

**Comment by Nickel33** [comment]
Four Types of Errors:
Error: Bad Battery Replace Now
Error: SD Card Problem
Error: Invalid Setup File
Error: Device Error 0xXX

Use an triangular icon in place of the rabbit and/or hand icon.

**Comment by jeff101** [comment]
I've discovered a couple more minor firmware bugs (with the new firmware).

To recreate them:
First bug - start with a device containing a valid MAT.cfg file. Open the SD and delete the file. Within 5 seconds Domino will report there isn't a valid setup file. Now add the setup file back. The channels will update to whether they are enabled or not, but the error message will remain. I've confirmed this is a firmware issue by issuing an STS in Tera Term (code 0x09).

Second. For this one first remove the battery and connect to USB. Again, start with a valid MAT.cfg file. Domino will report the battery is critically low (STS code 0X11 as expected). Now delete the MAT.cfg file and Domino will report the two errors (STS code 0x19). Now click start, and all mention of the low battery has disappeared. (STS code 0x09). The battery bit doesn't get set again until the MAT.cfg file is restored, and start is clicked.

**Comment by Nickel33** [comment]
The battery issue is not really a firmware problem.  It is by design.  The only 2 times the battery voltage is checked is:
1. On Powerup
2. Every time a 32K page is written to the SD card.
The symptoms you are describing are consistent with that behavior.  We can't fix the battery error.  We can suppress the MAT.cfg error.  I will write a new bug for how to do it.
