### ISSUE TITLE
MAT.cfg error

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#228]
When there is no MAT.cfg file, the status says MAT.cfg error. This may be distressing to a new customer with a blank SD card. Change to MAT.cfg file missing (or similar).

**Comment by jeff101** [comment]
I changed the error message to: Configuration file (MAT.cfg) missing or invalid

**Comment by Nickel33** [comment]
That works.  The only issue is that once the "missing" MAT.cfg file is replaced, the warning doesn't go away. This is a firmware bug, but I wish it had a hardware solution.

**Comment by Nickel33** [comment]
Verfied fixed as described.  0.6.4
