### ISSUE TITLE
Suppress MAT.cfg file errors 

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#230]
The MAT.cfg file error is almost always a red herring.  It usually means that the user just has not put the MAT.cfg file on the SD card yet, and because of the firmware behavior, it can't be cleared without starting the logger.  But this is very counter-intuitive:  who would start a logger that says that it is in an error state?

The only solution I can come up, short of magically updating the firmware in all the field devices, is to suppress the error.

**Comment by Nickel33** [comment]
To clarify, just suppress the message on the status screen.  Keep this pop-up:
![image](https://user-images.githubusercontent.com/3340259/73962308-28a30a00-48dc-11ea-9736-d4d6feb03f8d.png)

**Comment by jeff101** [comment]
Error messages will no longer be displayed on the status screen. From now on, when the "Start Running" button is pressed, Domino will query the logger (STS) and report any errors in a dialog as above.

**Comment by Nickel33** [comment]
Verified fixed. Closing.
