### ISSUE TITLE
Remove MAT logger driver installation from installer

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#235]
Windows 10 doesn't require installing the MAT logger driver, and since Windows 7 is no longer supported, it is unnecessary to install the driver.
![image](https://user-images.githubusercontent.com/8093093/75992696-58870280-5ec6-11ea-913f-88407df32b1b.png)
This will allow us to avoid errors like above

**Comment by Nickel33** [comment]
verified removed 1.0.0
