### ISSUE TITLE
Invalid descriptions are reverted without notification in some cases

### ISSUE THREAD

**Issue by GK-Lowell** [LowellInstruments/Domino#246]
If a user writes an invalid description (with spaces, non-viable characters, etc) and then clicks "save file" before clicking elsewhere, the usual error message about an invalid description doesn't pop up. Instead, the file name reverts without notice. This could cause confusion if a user finds that their description isn't what they thought it was upon retrieving the logger.

**Comment by Nickel33** [comment]
Done.  Nick to check.

**Comment by Nickel33** [comment]
Verified done!  Closing.
