### ISSUE TITLE
This data file doesn't convert

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#253]
[1412044_hTT8_sn1412044_(0).zip](https://github.com/LowellInstruments/Domino/files/6104208/1412044_hTT8_sn1412044_.0.zip)

I believe the problem is in the process page method of the CompoundProduct class. It would appear that the `shortest` is being calculated incorrectly. Rather than giving the length of the longest dimension, it's giving the total number of elements in the matrix.

**Comment by jeff101** [comment]
This problem needs to be solved in lowell-mat. Change the line to `process_page` to this:

`shortest = min([x.time.size for x in converted])`

**Comment by jeff101** [comment]
Fixed in lowell-mat

**Comment by Nickel33** [comment]
Verified fixed.  Closing.
