### ISSUE TITLE
Notify user when A/D values are zero for enabled channels.  Suggest reset.

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#257]
The magnetometer is sometimes getting stuck and reports all zero (pre-compensated) values.  This is confusing because the logger otherwise seems to be working and the compensated values are non-zero.  So, we should notify the user when the magnetometer binary values are zero and suggest a software reset.  It is a clunky workaround for a firmware bug, but better clunky than nothing.

**Comment by jeff101** [comment]
If the magnetometer reports zeros for the raw values three readings in a row, then indicate that there is a possible problem with the logger and we recommend a reset. Give them the option to reset or dismiss.

**Comment by Nickel33** [comment]
Looks good.  Closing.
