### ISSUE TITLE
Attempt to prevent customer from converting lid files while connected via USB

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#258]
STORY
The MAT-1 USB connection is not a high speed connection and it is not sufficient to convert a data file. Not only is the conversion extremely slow, but there is reason to believe it can crash the device. 

DONE
Ideally, definitively determine if the file on the MAT-1 and raise a warning
If that's not possible, determine if the file is in the root directory and raise a warning that the file MAY be on a device.

**Comment by jeff101** [comment]
If the file is on your C drive then no warning. If the file is on a removable disk, pop a warning that it's recommended that you copy the file from the memory card to your local disk before converting.

**Comment by Nickel33** [comment]
#258 is duplicate.  Closing.
