### ISSUE TITLE
Slow communications and file conversion speed for experimental build

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#259]
Story:  Windows 10 is sending a "reset USB device" command to the logger for poorly understood reasons.  We want to see if reducing the frequency of commands and file conversion rate prevents this error.  This may become part of a fix to the "Green LED" firmware bug, but for now we need to see if it changes the behavior of Windows and the logger.

Done: Add delay between all CDC commands.  Add delay when reading .lid file and writing .csv files. Delay should be easily modified for testing. Start with 10 ms.

**Comment by jeff101** [comment]
Discussed this with Nick. Wasn't helping. Closing
