### ISSUE TITLE
Provide more informative feedback when a file won't open in Converter

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#30]
As a user, if a file fails to open in converter, I want to know more than that there was an error, I want to know what type of error and if the entire file is corrupt or just a small part.

**Comment by jeff101** [comment]
That was related to Domino-64 so I put it on the same branch.

**Comment by jeff101** [comment]
To test, try opening a .lid file that was started in delayed start mode, but was stopped before it reached the start time.
Or, when adding a file, put *.* in the filename field to reveal all files. Choose a file that is not .lid

**Comment by Nickel33** [comment]
0.5.8 Much improved behavior.  Closing.
