### ISSUE TITLE
Convert all the valid pages in a .lid file

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#32]
STORY
As a user, I want my .lid file converted even if there is a bad page or two.  Convert the good pages and notify me that there are bad pages.  That way I won't have a heart attack when the entire file fails to convert when it is only the last page out of many pages that is bad.

**Comment by Nickel33** [comment]
There  are three desired states:
1. File is good.
2. File has one or more bad mini-headers beyond the first mini-header. A warning should come up that states that X bad pages out of Y total are corrupt.
3. Totally corrupt from page 1.  Contact support@lowellinstruments.com for help with this file.

**Comment by jeff101** [comment]
This will be partly solved in lowell-mat https://github.com/LowellInstruments/lowell-mat/issues/126

**Comment by jeff101** [comment]
Maybe you have some thoughts on the wording? I didn't want to introduce the concept of data pages. Does it make sense to say you encountered corruption at a percentage?
![image](https://user-images.githubusercontent.com/8093093/66047540-efa1f580-e4f5-11e9-875c-0f93d925949c.png)

**Comment by Nickel33** [comment]
Basically looks good.  Maybe say "encountered corruption at 79% _**from the start of the file**_."  But this will do the job and will help keep users from thinking then entire file is shot.  

Also add "Contact support for help with this issue."

**Comment by jeff101** [comment]
Message updated

**Comment by Nickel33** [comment]
Done. Closing.
