### ISSUE TITLE
Converting to current without magnetometer/accelerometer enabled is confusing

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#34]
STORY
As a user, I selected an output type of "Current" by accident on a file that didn't have the magnetometer and accelerometer channels enabled.  The file did not convert but I didn't notice right away because other files in the list did convert.  When I went and looked for the temperature output file from the file without the accl and mag enabled, I didn't see it and was confused.  I tried converting again and eventually noticed the "X" next to the file and wondered what that was.  Without specific feedback, I was confused.

**Comment by Nickel33** [comment]
There needs to be some indication that a file that was converted does not support the conversion type. I.e. converting to current without the accelerometer and/or magnetometer enabled.

**Comment by jeff101** [comment]
This was resolved in 0.6.2

**Comment by Nickel33** [comment]
The "Error" status makes it clear that something went wrong.  But it is not very informative.  Closing.
