### ISSUE TITLE
Support Display Magnification

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#42]
STORY:
As a user with lousy vision, I want to be able to use scaling and display magnification with Windows 7 and 10 and I expect the application GUI to still work correctly.

Basically, I want it to work, and it doesn't work with MAT Logger Commander.

**Comment by Nickel33** [comment]
For what it is worth, "Converter" doesn't play nice with scaling at 150% on Windows 10.  The "Options" window is too small and crowded.

**Comment by Nickel33** [comment]
This issue appears to be Windows 10 specific.

**Comment by jeff101** [comment]
This was addressed in Domino-69. Screen magnifier also works.
