### ISSUE TITLE
Error when converting file is not very helpful

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#60]
STORY
As a user of the software, I want to get more feedback as to what is wrong with my data file when something is out of order.

See the two files that are attached for an example of the not-a-lot-of-feedback-issue.
[S1810607_1_Hz_(0).zip](https://github.com/LowellInstruments/Logger/files/2521936/S1810607_1_Hz_.0.zip)

**Comment by jeff101** [comment]
Support for .lis files is currently not supported.
