### ISSUE TITLE
Scroll bar comes up when it is not needed in Convert Files tab

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#66]
STORY
As a user, when I see a scroll bar I expect that part of the information available is hidden off the screen.  I am surprised when that is not the case.

Specifically, when the convert files screen is populated with files, a horizontal scroll bar appears. But moving the scroll bar left and right does not show any hidden column, rather it just shifts by a pixel or two.

**Comment by jeff101** [comment]
Now that the size of the main window is adjustable, this isn't a bug, it's a _feature_
