### ISSUE TITLE
Add ability to split large .lid files

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#74]
STORY:
I am a personal computer and have only limited memory.  I can't open a 2-3 GB .lid file  nor can I manage a 10-20 GB .txt file.  I need a way to split the file into easily manageable chunks when parsing it.

Details:
At a minimum, we need support that is the same as MLC.

**Comment by jeff101** [comment]
This has been implemented in the back-end. Now we just need to decide where to put the option in the GUI. Adding it to the "file output options" dialog would seem to be the logical place. At the bottom of  "general" tab? Or maybe on it's own tab?

**Comment by Nickel33** [comment]
I think it should go user "File Output Options".

**Comment by Nickel33** [comment]
Per our conversation on 12/21:
Put "Split file" in a new tab under options.
Move Average Burst to the new tab.
Move Output format to the new tab.
Move declination adjustment to the main window (replacing output format).

**Comment by Nickel33** [comment]
Verified fixed 0.5.8.
