### ISSUE TITLE
Add ability to do a software reset of the logger

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#75]
STORY:
As a technical support representative, I need a way for a customer to reset their logger using Domino without needing to power-cycle the logger.

Since there is no "Close Port" button, add a key command of CTRL-SHFT-R to do a software reset.

**Comment by jeff101** [comment]
To perform a reset, hold down ctrl-shift and click the running status icon

**Comment by Nickel33** [comment]
Works!  Fixed. Closing!
