### ISSUE TITLE
Add option to output "Voltage"

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#86]
Make it possible to convert the "voltage" as an output file.

**Comment by Nickel33** [comment]
Add to "options" menu?

**Comment by jeff101** [comment]
Under "File output options", Change "Calibration coefficients (advanced)" to "Advanced". Then have "output voltage" as a checkbox option.

**Comment by Nickel33** [comment]
The time format does not follow the time format setting. It is always ISO time, not Legacy, POSIX or elapsed time.

**Comment by scottiey1** [comment]
@jeff101 I have been working with Domino using BootCamp and running the following version of Windows. When I convert the file with the Voltage checked I get a pop up that says Conversion Error - The re were errors during the file conversation. In Show More is says - myfilename.LID: File Structure error.
Nick mentioned a 3rd file should be written for voltage only. This does not occur. 
Keep in mind this could be a Mac/Bootcamp things only as it works fine on a native Windows machine.

Edition	Windows 10 Home
Version	21H2
Installed on	‎6/‎13/‎2022
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by jeff101** [comment]
@Nickel33 It was a bit tricky to get this working and I didn't have a lot of flexibility in the way I set it up. Since this is more of a debug feature, I figured it would be okay to just output a single time format?

**Comment by Nickel33** [comment]
Well it is confusing to have it appear to be supported but not work as expected.  For now, how about you just append "ISO Time " so it reads "Output Voltage Values to File (ISO 8061 Time)".

**Comment by Nickel33** [comment]
Fixed.  Closing.
