### ISSUE TITLE
Add licensing info to the about box?

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#94]
Should the licensing info be added to the about box? 

If yes, what exactly should it say?

If no, where should the licensing info be displayed? On the download page?

**Comment by mo-nathan** [comment]
There is no strict requirement here.  However, I do recommend that you provide a copyright notice along the lines of:

Copyright 2018-2019 by Lowell Instruments, some rights reserved.
Source code for this application is available under the GPLv3 License at http://github.com/LowelInstruments/Domino

**Comment by Nickel33** [comment]
Verified fixed 0.5.8. Closing.
