### ISSUE TITLE
Change color of the icon to better match the LI logo

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#95]
The purple icon look okay, but it would be better if it matched the LI icon colors somehow or was black and white (not so it matches the real-life dog, but so it doesn't clash with the LI logo.)

**Comment by jeff101** [comment]
Have a look at the icon branch

**Comment by Nickel33** [comment]
That looks better.  One more place to change:  In the Info box, change the "!" icon to the Domino icon.

**Comment by jeff101** [comment]
![image](https://user-images.githubusercontent.com/8093093/52014425-7d33ce00-24ad-11e9-84ea-01c090a07922.png)

I just changed the info icon to the Domino icon and I don't like it as much. It kind of just looks like a decoration and it isn't clear to me that it's an info button. What do you think?

**Comment by Nickel33** [comment]
The "I" icon in 0.5.8 looks good.  Closing issue.
