### ISSUE TITLE
Logger Status is not obvious enough

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#96]
The status of the logger is not obvious enough.

There are really two different high-level pieces of information that need to be communicated to the user.
1. The device is connected/is-not-connected.
2. The device is running/delayed/stopped/in-an-error-state.

I propose splitting the two pieces of information up.  The connected or not connected status could be a USB connector and the logger with data.  Something like this:
![image](https://user-images.githubusercontent.com/3340259/50306207-e235e600-0462-11e9-9e31-09339806d1bb.png)
It should also contain text.  "Logger is connected to USB."
If a logger is not connected the logo could be:
![image](https://user-images.githubusercontent.com/3340259/50306397-7142fe00-0463-11e9-96e2-8cf582039eb4.png)
with the text: "No Logger Detected"

The running/delayed/stopped/in-an-error-state would have a another set of icons.  The rabbit works for run.  The stop sign works for stop. But icons are needed for error and delayed.  I am open to suggestions.

**Comment by jeff101** [comment]
![image](https://user-images.githubusercontent.com/8093093/51688922-92978c80-1fc3-11e9-824a-9d8731389996.png)

**Comment by jeff101** [comment]
![image](https://user-images.githubusercontent.com/8093093/51688934-988d6d80-1fc3-11e9-8b55-c57388de5769.png)

**Comment by jeff101** [comment]
![image](https://user-images.githubusercontent.com/8093093/51688952-a2af6c00-1fc3-11e9-8c09-efbc3d00be28.png)

**Comment by jeff101** [comment]
Status will be moved from the the top, as pictured above, to a status bar on the bottom of the window.

**Comment by Nickel33** [comment]
Looks good in 0.5.8.  Closing.
