### ISSUE TITLE
Implement custom calibration coefficients

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#97]
STORY:
As an advanced user I would like to be able to use custom calibration coefficients when converting a data file. Currently the GUI offers this feature, but it isn't implemented in code.

DONE:
Implement it in code.

**Comment by jeff101** [comment]
I'm intentionally NOT making the custom calibration file sticky, but I will keep track of the last directory a file was loading from.

**Comment by Nickel33** [comment]
The feature has been implemented but there is a related bug #113 that is still open.  Closing this one based on PR 115.
