### ISSUE TITLE
Add a help dialog to the declination (?) button

### ISSUE THREAD

**Issue by jeff101** [LowellInstruments/Domino#98]
STORY
As a user, I may not understand the purpose of the declination text box on the converter screen. The developers were gracious enough to add a help button to the text box, however it's currently not enabled.

DONE
Upon clicking the help button, a dialog pops up with a brief explanation of how declination is applied.

**Comment by jeff101** [comment]
On branch declination

**Comment by Nickel33** [comment]
Other that the government shutdown, Fixed in PR 115.
