### ISSUE TITLE
Non-ISO time formats are not working

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#99]
The three "non-ISO" time formats are not working in the current branch of "bugs". It always gives me ISO Time.

Legacy used to work but doesn't any more.  (I am not sure about elapsed time or POSIX time.)

**Comment by jeff101** [comment]
This appears to be working fine on the split_file branch which is a descendant branch of bugs.

**Comment by Nickel33** [comment]
They work now in PR 115.
